name = "traffic-counter-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "6b334c20eaac18dc9726fea343353d7e"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "traffic-counter-db"
database_id = "98630067-a7f0-4bd0-8d63-1155dc293af9"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.production.d1_databases]
binding = "DB"
database_name = "traffic-counter-db"
database_id = "98630067-a7f0-4bd0-8d63-1155dc293af9

[[triggers.crons]]
cron = "*/15 * * * *"